### ISSUE TITLE
Slabs attacking players (shulkers)

### ISSUE THREAD

**Issue by altrisi** [InventivetalentDev/AdvancedSlabs#12]
## What steps will reproduce the problem?
1. Spawn a Advanced Slab
2. Be in Survival or Adventure gamemode
3. Wait
## What were you expecting to happen? What happened instead?

I think that the Shulkers in slabs don't have to attack. But if you are near to an slab, it will start attacking you.
## What version of the plugin are you using? _Type /version AdvancedSlabs_

I'm using AdvancedSlabs version 1.7.2
## What Spigot version are you using? _Type /version_

I'm using git-Spigot-90f61bc-5e5cf84 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)
## What plugins are you using? _Type /plugins_

I'm using AsyncWorldEditInjector, PermissionsEx, WorldEdit, AdvancedSlabs, AsyncWorldEdit, NametagEdit, ActionBarAPI, VoidWorld, Multiverse-Core, ChatAPI, AsyncWorldEdit-ActionBarAPI
## Do you have an error log? Use [pastebin.com](http://pastebin.com). _If you're not sure, upload your whole server log_

No, I haven't
## Did your client crash? _Upload errors in .minecraft/logs/latest.log as well_

No, it didn't crash.
## Additional information?  _(Are you using Bungeecord? Did it work in previous versions? etc.)_

No

To correct this error, I'm adding the {NoAI:1} tag manually to all Shulkers in the area, but I think it can be added to be autoadded when the slab is created.

**Comment by InventivetalentDev** [comment]
The only time this could happen is if you uninstalled the plugin while the slabs were still 'alive'.
The plugin already spawns custom shulker entities (i.e. with AI disabled, etc.), so it shouldn't be possible for them to attack.

**Comment by altrisi** [comment]
The shulkers attack players even when they are generated in that moment. I never uninstalled the plugin from the test server where I am using the plugin in this moment.

**Comment by altrisi** [comment]
You can check it in this video: [Click here](https://www.dropbox.com/s/5yzafeuwx1q3dms/AdvancedSlabs%20have%20AI.mp4?dl=0)

**Comment by InventivetalentDev** [comment]
Are you absolutely sure there are no errors in your console? If the plugin fails to disable the AI, there should at least be something saying why it failed.

**Comment by altrisi** [comment]
Zero errors.

**Comment by altrisi** [comment]
PS: In the video, the slabs can't launch ShulkerBullet entities because I have a repeating command block killing them just when they spawn.

**Comment by altrisi** [comment]
Closing as stale.
