### ISSUE TITLE
Right clicking slab with wand causes Java error

### ISSUE THREAD

**Issue by nomadjimbob** [InventivetalentDev/AdvancedSlabs#15]
## What steps will reproduce the problem?  
1. Create a slab with the editor wand
2. Place slab on ground
3. Right click on the slab to move

## What were you expecting to happen? What happened instead?  
Expected the slab to highlight and "You are now editing this block" to appear. Instead nothing happens and the java error appears on the server console

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
1.8.2

## What Spigot version are you using? *Type /version*  
1.12.2

## What plugins ae you using? *Type /plugins*  
Multiverse Core 2.5.0
Multiverse Portals 2.5.0
ProtectionLib
ProtocolLib
Vault

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
https://pastebin.com/vtRqYPPt

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No

**Comment by Paperboypaddy** [comment]
Hmm I have the same issue. I'm on spigot 1.12 running Version 1.8.2 of AdvancedSlabs. Only thing different, I'm not getting any errors.
