### ISSUE TITLE
Slab dissapearing

### ISSUE THREAD

**Issue by HeadlessJoey** [InventivetalentDev/AdvancedSlabs#8]
## What steps will reproduce the problem?  
1. Pick a block (for example a normal stone block).
2. Place the Slab on top of the block it was made from (so put down a stone block and put the slab on top of it)
3. Now as you lower the slab into the stone it will dissapear and only show a shulker head (So lower the stone slab into the stone below it)

## What were you expecting to happen? What happened instead?  
Normally the slab just lowers, take any other block under the slab and the slab will not dissapear but if it's the same block then it will glitch and dissapear to only show the shulker head.

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
1.7.1
## What Spigot version are you using? *Type /version*  
1.10-R0.1-

## What plugins are you using? *Type /plugins*  
(You spelled "are" wrong and it was "ae") The list is too long and I doubt the plugins I use impact this issue. If so then I can link them all.

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
No logs.

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
Nope.

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
I think this was already happening in some previous versions and nope not using Bungeecord.

**Comment by InventivetalentDev** [comment]
Type `/as respawn` to respawn the slab when it disappears. There's currently no reliable way to automatically respawn it properly, since this seems to be a bug in the Minecraft client.
